### ISSUE TITLE
dev-python/pcapy merged to main tree

### ISSUE THREAD

**Issue by gentoochainsaw** [barzog/barzog-gentoo-overlay#6]
Thank you for your work on packaging pcapy. I have taken your ebuild through the ebuild review process and made some minor modifications in the process. Credited you in the commit message, of course:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=a05e0ba49f1f767a966603b315624eba6240631a

I see your process is to delete what is mainlined, so you can delete it from your overlay now. If you wish to be credited by your full name, or in a different way, please let me know!

**Comment by barzog** [comment]
Done.
