### ISSUE TITLE
sci-geosciences/mapnik-world-boundaries Manifest is outdated

### ISSUE THREAD

**Issue by gen2** [barzog/barzog-gentoo-overlay#7]
The checksums for the following files are wrong (probably just outdated):

- ne_10m_populated_places.zip
- ne_110m_admin_0_boundary_lines_land.zip

Would be nice if you can fix this.
Thanks!

**Comment by barzog** [comment]
Fixed.
--- /var/lib/layman/barzog-overlay/sci-geosciences/mapnik-world-boundaries/Manifest     2018-04-14 11:25:25.060972757 +0300
+++ Manifest    2018-04-14 11:21:32.979607299 +0300
@@ -1,5 +1,5 @@
-DIST ne_10m_populated_places.zip 1578296 SHA256 cf53889b6631704361d1ac86ad9f5294b29595e6cdbbdb6a4025de2fb9753b59 SHA512 2e4690543001788021c0f5692645068dc61ed6e3202c19da1af733f65bccce3543e04214cfd8a6727e3587e263f1d034333c02b2e514fac413b6e0d25007bcab WHIRLPOOL 6e4be9e2f73630466dcdd1919fb5b5565afc72381423fdf9646c3cf549caebed79c212f25a96124393e4f62806013f04a936ccaab6b0b46953308bb2036ec757
-DIST ne_110m_admin_0_boundary_lines_land.zip 44731 SHA256 0597399113a902a79e585b5cb0cb93d7631a6fc99515f220d5b979bc61ced99e SHA512 78d6a032228976bc4c37022fd3d6169798c4d77e36b21d62874e8990070e18738f6ad4b811b189c5d4a899a80eb8ba4d8d490f686c21487a46d295941f015a70 WHIRLPOOL 02be8e35c9fe5481db5042dac79924985d9498e73febc218c3340ed5c61b62e8a347e01992aa62ce3bc7042aafe9a6799ec505f303dd873fdd32b5d0632e9013
+DIST ne_10m_populated_places.zip 2002618 SHA256 2cce48b70848a98d72d974b98b5c51f1607ce2b56044165358aa7dc002187ab9 SHA512 44f0b6bd169a19866154658a722b0bbc9a51659356dc6e7d88d74864421315daf6fe67c5a9aaae362fb050072a64ea5436abdf31cb1f4d85572dc89bb13d9687 WHIRLPOOL 2c6bb645e7180adb38a2a1111afb7a2c5cd8bd7be1be6b0054ed80e73091a0b33786cf82bfe30104cce9f7660d0cad699c0e79ee21f172bf063269e1ae1e0701
+DIST ne_110m_admin_0_boundary_lines_land.zip 45804 SHA256 70e1885d9e1252988db41045fb1a2829587e31eddaa92c3c56af354d49868e34 SHA512 a6970aaf525bc4c8dc5b2ee0daee8f42fa4d6774c0cacd50567be74a142fc2d3bf29e64a697ca8cfa88fecad76e0296ec65a4236afdbe36ebe0a589e634b42c6 WHIRLPOOL 7f49e4cb74734288b8c9d36b04eb40a4860431a7ef9cfae988aad2bb935372bd64d67ea7ba2a7824c11e5ae59851fcc4d6a82901cd2262c954383f14d1c75081
 DIST processed_p.tar.bz2 409468857 SHA256 76ae96a665f5ff9c9caa63ea73c12c0932379f6c8d1e29df741f437d3a54ee5f SHA512 a6fc370af94ac7fba51e18aa19b2de97778029aaa157fb17df38e7c6863aa01ec8261df48f21ac9cc720bd626038eb3758352dc0448405a454fe3c541dbda5fa WHIRLPOOL 3036ac2a8196d2ba20f0d309873ded893537a699bbe191f4c4fefb51f8c7ba04df006658b7605c0d2e167d1c9f14959af7c8327483043ad1304b3d3f6b3bda21
 DIST shoreline_300.tar.bz2 43867136 SHA256 a15c476f2993c52621e1ba20b6a468fe7f6fb31e55125c74c656146d6e8f599d SHA512 5c6aad567cc10d91bbbf5c1816059d763782d624ab767d4d112e23719db5d21e4856b57a942841e19228fb5fd93cb1b9c66e2142d0843250b4f3046aee1c220f WHIRLPOOL 4317d4fd08e760baa76c47ebfad106f07f038e9dde4f4eaee531d7f47576b47a648aa08c2b9e1fa3fac9cf0d525d1f67f84d4dfcaf622991d8fc7a00815f2657
 DIST world_boundaries-spherical.tgz 52857349 SHA256 b3c38baffcc4888dafe98f9d98efc877a6b62a2ab6aaa11592ac8460908a0ce9 SHA512 2d83049688b52987ffa26afb25a340dd1f68f22fe8fbf8e5ca10a798e34cde9c6e4508c44edf86cd46f7ab3d154b123cbbd6084f8b7087c5fbb4c6a14b9cc69d WHIRLPOOL e14a38e51a934db26f50edaf227c575021b204d203ad5ad5ce575948cf258fc9eabcb76381baba7fcbc4da5a1a67c81f7b1b341a15bacfab30d9a7ab77264ce2

**Comment by thbeutin** [comment]
It's broken again:

!!! Fetched file: ne_10m_populated_places.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2807425
!!! Expected: 2002618
!!! Couldn't download 'ne_10m_populated_places.zip'. Aborting.
!!! Fetched file: ne_110m_admin_0_boundary_lines_land.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      45820
!!! Expected: 45804
!!! Couldn't download 'ne_110m_admin_0_boundary_lines_land.zip'. Aborting.

Should i open another issue for this?

**Comment by barzog** [comment]
Fixed
