### ISSUE TITLE
sci-geosciences/mapnik-world-boundaries Manifest is outdated

### ISSUE THREAD

**Issue by thbeutin** [barzog/barzog-gentoo-overlay#8]
It's a dupe of issue #7, but since i cannot reopen it i created this one.

!!! Fetched file: ne_10m_populated_places.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      2807425
!!! Expected: 2002618
!!! Couldn't download 'ne_10m_populated_places.zip'. Aborting.
!!! Fetched file: ne_110m_admin_0_boundary_lines_land.zip VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      45820
!!! Expected: 45804
!!! Couldn't download 'ne_110m_admin_0_boundary_lines_land.zip'. Aborting.

**Comment by barzog** [comment]
Fixed
